# -*- coding: utf-8 -*-
"""sales data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1co-d4yFm2Ud2yUdO8A9CvfZlg_xu54_Z
"""

import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

df=pd.read_csv('/content/Untitled spreadsheet - superstore_sales.csv')
df.head()

df.shape

df.info()

df.columns

df.isnull().sum()



df.describe()

df['order_date'].min()

df['order_date'].max()

df.order_date=pd.to_datetime(df.order_date).dt.strftime('%Y-%m')
df.order_date



df_trend=df.groupby('order_date').sum()['sales'].reset_index()
df_trend





plt.plot(df_trend['order_date'],df_trend['sales'])

plt.figure(figsize=(15,6))
plt.plot(df_trend['order_date'],df_trend['sales'])
plt.xticks(rotation='vertical')
plt.show()

#top 10 products

df.head()

df.product_name

df_trend1=df.groupby('product_name').sum()['sales'].reset_index()
df_trend1

df_trend1=df_trend1.sort_values('sales',ascending=False)

df_trend1.head(10)

#most selling products

df_trend2=df.groupby('product_name').sum()['quantity'].reset_index()
df_trend2

df_trend2=df_trend2.sort_values('quantity',ascending=False)
df_trend2.head(10)

#preffered ship mode

sns.countplot(df['ship_mode'])

df['ship_mode'].value_counts()

